name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp://ftpupload.net
          username: ${{ secrets.if0_36932547 }}
          password: ${{ secrets.AxthlHhlVgi }}
          local-dir: "../../Web Pengelola Data Prodi v2"
          server-dir: "/manajemen-prodi.portofolio.great-site.net/htdocs"
